@BaseUrl = http://localhost:3080/api/v1
@BaseUrlUsers = http://localhost:3080/api/v1/users
@email = emailValid@gmail.com
@password = password
@auctionEnd = 2027-01-01T00:00:00Z

### Create new user
POST {{BaseUrlUsers}}/signup
Content-Type: application/json

{
    "user_name": "name",
    "password": "{{password}}",
    "bio": "text nome muito curto",
    "email": "{{email}}"
}

### Login
POST {{BaseUrlUsers}}/login
Content-Type: application/json

{
    "password": "{{password}}",
    "email": "{{email}}"
}

### Create new product
# Run Login before this request so the session cookie is available.
POST {{BaseUrl}}/products/
Content-Type: application/json

{
    "product_name": "Sample Product",
    "description": "This is a sample product description.",
    "baseprice": 99.99,
    "auction_end": "{{auctionEnd}}"
}

### Logout
POST {{BaseUrlUsers}}/logout

### Pegar token CSRF
GET {{BaseUrl}}/csrftoken


###
WEBSOCKET ws://localhost:3080/api/v1/products/ws/subscribe/0d7abb9a-e5d8-4cde-9608-385761742b92
